_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
batch_size:
    value: 128
batch_tokens:
    value: 32
embedding_dim:
    value: 4096
expansion_factor:
    value: 8
hidden_dim:
    value: 32768
learning_rate:
    value: 0.0001
num_epochs:
    value: 10
penalty_coeff:
    value: 0.05
